# Generated by Django 2.0 on 2018-05-26 11:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name')),
                ('stars', models.IntegerField(db_column='stars', null=True)),
                ('lore', models.TextField(blank=True, db_column='lore', null=True)),
                ('effect', models.TextField(blank=True, db_column='effect', null=True)),
                ('materials', django.contrib.postgres.fields.jsonb.JSONField(db_column='materials', null=True)),
                ('attack', models.TextField(db_column='attack', null=True)),
                ('defense', models.TextField(db_column='defense', null=True)),
                ('pendulumLeftScale', models.IntegerField(db_column='pendulum_left_scale', null=True)),
                ('pendulumRightScale', models.IntegerField(db_column='pendulum_right_scale', null=True)),
                ('pendulumEffect', models.TextField(db_column='pendulum_effect', null=True)),
            ],
            options={
                'db_table': 'ygo_card',
            },
        ),
    ]
