version: '3'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  database:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment: 
      - POSTGRES_USER=ygo_i2_user
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/app
    links:
      - database